server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products,/api/products/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory,/api/inventory/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders,/api/orders/**
