server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - name: Path
                  args:
                    patterns:
                      - /api/products
                      - /api/products/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - name: Path
                  args:
                    patterns:
                      - /api/inventory
                      - /api/inventory/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - name: Path
                  args:
                    patterns:
                      - /api/orders
                      - /api/orders/**
